# Generated by Django 6.0.4 on 2026-04-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.loja'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='loja',
            unique_together={('nome', 'localizacao', 'bairro')},
        ),
    ]
