# Generated by Django 6.0.4 on 2026-04-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_loja_alter_loja_bairro_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loja',
            unique_together=set(),
        ),
    ]
