# Generated by Django 6.0.4 on 2026-04-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_loja_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loja',
            unique_together={('nome', 'localizacao', 'bairro')},
        ),
    ]
